### ISSUE TITLE
Error: WebSocket is not open. Ready state is: 3

### ISSUE THREAD

**Issue by torrinworx** [torrinworx/OpenGig.org#10]
Got this finally after messing around with signup/login Auth.jsx stuff.

Not sure what the cause is. It could just happen when vite/the server is shut down or the connection is inturrupted? Might just need to handle websocket disconnection on the client a bit better. Only really able to see it when the server goes down:
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState#websocket.closed

To repro locally:
1. Start server.
2. Load the login page in the browser.
3. In backend/index.js comment out an import to force vite to crash/throw an error without properly closing the websocket:
```
// import { OArray } from "destam";
import { coreServer } from "web-core/server";

const connection = async (ws, req, user, sync) => {
	sync.notifications = OArray([]);

	return;
};

coreServer(
	'./backend/jobs',
	process.env.ENV === 'production' ? './dist' : './frontend',
	connection
);
```
4. Output should be something like this:
```
[nodemon] restarting due to changes...
[nodemon] starting `node ./backend/index.js`
Server running on port 3000
Connected to mongodb
Job "authenticated" loaded
Job "unauthenticated" loaded
Job "login" loaded
Job "signup" loaded
All jobs loaded.
file:///home/torrin/Repos/Personal/OpenGig.org/backend/index.js:5
        sync.notifications = OArray([]);
        ^

ReferenceError: OArray is not defined
    at connection (file:///home/torrin/Repos/Personal/OpenGig.org/backend/index.js:5:2)
    at file:///home/torrin/Repos/Personal/OpenGig.org/web-core/server/coreServer.js:109:49
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.17.0
[nodemon] app crashed - waiting for file changes before starting...
```
5. Try to login:
```
[vite] connecting... [client:495:8](http://localhost:3000/@vite/client)
[vite] connected. [client:614:14](http://localhost:3000/@vite/client)
WebSocket connection closed. [coreClient.jsx:116:16](http://localhost:3000/@fs/home/torrin/Repos/Personal/OpenGig.org/web-core/client/coreClient.jsx)
[vite] server connection lost. Polling for restart... [client:556:14](http://localhost:3000/@vite/client)
Uncaught (in promise) Error: WebSocket is not open. Ready state is: 3
    jobRequest coreClient.jsx:61
    jobRequest coreClient.jsx:35
    handleLogin Auth.jsx:83
    handleSubmit Auth.jsx:22
    onMouseDown Button.jsx:122
    hypertext h.jsx:75
    sigs h.jsx:225
    hypertext h.jsx:225
    update destam-dom.js:379
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:391
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    call chunk-EEVSAJ6E.js:45
    callListeners chunk-EEVSAJ6E.js:56
    listenerContext chunk-W6NKKAUB.js:109
    parentListener chunk-W6NKKAUB.js:164
    call chunk-EEVSAJ6E.js:45
    callListeners chunk-EEVSAJ6E.js:56
    listenerContext chunk-W6NKKAUB.js:109
    mutable chunk-W6NKKAUB.js:888
    switchAction Auth.jsx:76
    onMouseDown Button.jsx:122
    hypertext h.jsx:75
    sigs h.jsx:225
    hypertext h.jsx:225
    update destam-dom.js:379
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:391
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:391
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:391
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:391
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:399
    coreClient coreClient.jsx:129
    async* index.jsx:68
[coreClient.jsx:61:19](http://localhost:3000/@fs/home/torrin/Repos/Personal/OpenGig.org/web-core/client/coreClient.jsx)
    handleSubmit Auth.jsx:22
    AsyncFunctionThrow self-hosted:804
    (Async: async)
    onMouseDown Button.jsx:122
    (Async: EventListener.handleEvent)
    hypertext h.jsx:75
    sigs h.jsx:225
    map self-hosted:175
    hypertext h.jsx:225
    update destam-dom.js:379
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:391
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    mount destam-dom.js:399
    defer destam-dom.js:499
    callAllSafe destam-dom.js:186
    update destam-dom.js:385
    call chunk-EEVSAJ6E.js:45
    callListeners chunk-EEVSAJ6E.js:56
    listenerContext chunk-W6NKKAUB.js:109
    parentListener chunk-W6NKKAUB.js:164
    call chunk-EEVSAJ6E.js:45
    callListeners chunk-EEVSAJ6E.js:56
    listenerContext chunk-W6NKKAUB.js:109
    mutable chunk-W6NKKAUB.js:888
    switchAction Auth.jsx:76
```

**Comment by torrinworx** [comment]
Should be fixed with #10
